default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: stock_api_development

test:
  <<: *default
  database: stock_api_test

production:
  <<: *default
  database: stock_api_production
